service: nodeless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject # Buscar informações sobre um objeto armazenado no S3
        - s3:PutObject # Salvar arquivos dentro do S3
      Resource:
        - "arn:aws:s3:::*" # Acesso a todos os buckets do S3

functions:
  hello:
    handler: handler.hello
